package OlaApp;

/**
* OlaApp/OlaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OlaApp.idl
* Quarta-feira, 16 de Outubro de 2019 14h14min14s GFT
*/

public final class OlaHolder implements org.omg.CORBA.portable.Streamable
{
  public OlaApp.Ola value = null;

  public OlaHolder ()
  {
  }

  public OlaHolder (OlaApp.Ola initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OlaApp.OlaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OlaApp.OlaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OlaApp.OlaHelper.type ();
  }

}
