package OlaApp;


/**
* OlaApp/OlaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OlaApp.idl
* Quarta-feira, 16 de Outubro de 2019 14h14min14s GFT
*/

public interface OlaOperations 
{
  String msg ();
  void msg (String newMsg);
} // interface OlaOperations
