package OlaApp;


/**
* OlaApp/Ola.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OlaApp.idl
* Quarta-feira, 16 de Outubro de 2019 14h14min14s GFT
*/

public interface Ola extends OlaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ola
