/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int x;
	int y;
};
typedef struct numbers numbers;

#define SIMP_PROG 0x2fffffff
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(numbers *, CLIENT *);
extern  int * soma_1_svc(numbers *, struct svc_req *);
#define sub 2
extern  int * sub_1(numbers *, CLIENT *);
extern  int * sub_1_svc(numbers *, struct svc_req *);
#define mult 3
extern  int * mult_1(numbers *, CLIENT *);
extern  int * mult_1_svc(numbers *, struct svc_req *);
#define div 4
extern  int * div_1(numbers *, CLIENT *);
extern  int * div_1_svc(numbers *, struct svc_req *);
#define resto 5
extern  int * resto_1(numbers *, CLIENT *);
extern  int * resto_1_svc(numbers *, struct svc_req *);
#define potencia 6
extern  int * potencia_1(numbers *, CLIENT *);
extern  int * potencia_1_svc(numbers *, struct svc_req *);
#define maior 7
extern  int * maior_1(numbers *, CLIENT *);
extern  int * maior_1_svc(numbers *, struct svc_req *);
#define menor 8
extern  int * menor_1(numbers *, CLIENT *);
extern  int * menor_1_svc(numbers *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
#define sub 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define mult 3
extern  int * mult_1();
extern  int * mult_1_svc();
#define div 4
extern  int * div_1();
extern  int * div_1_svc();
#define resto 5
extern  int * resto_1();
extern  int * resto_1_svc();
#define potencia 6
extern  int * potencia_1();
extern  int * potencia_1_svc();
#define maior 7
extern  int * maior_1();
extern  int * maior_1_svc();
#define menor 8
extern  int * menor_1();
extern  int * menor_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
